D:\applications\MSSQL16.SQLEXPRESS\MSSQL\DATA\

select * from salespersons;
select * from sales;
select * from sales where year(purchase_date)=2022;

select sm.salesman_id,count(sales.salesman_id) as total_sale_by_salesman 
from salespersons sm 
join sales on sm.salesman_id=sales.salesman_id
group by sm.salesman_id;
--2. What is the total number of cars sold by each salesperson?
SELECT sm.salesman_id, COUNT(sales.salesman_id) AS total_sale_by_salesman 
FROM salespersons sm 
JOIN sales ON sm.salesman_id = sales.salesman_id
GROUP BY sm.salesman_id;
select * from salespersons;
select * from cars;
select * from sales;
--
select count(car_id) from sales group by car_id;
--3. What is the total revenue generated by each salesperson?
select sum(c.cost) as sum_of_cars,s.salesman_id from cars c right join sales s
on c.car_id=s.sale_id
group by s.salesman_id;

SELECT SUM(c.cost) AS sum_of_cars, s.car_id
FROM cars c
JOIN sales s ON c.car_id = s.car_id
WHERE s.car_id = 1
GROUP BY s.car_id;
--get the individual revenue for each car sold
select sum(c.cost) as sum_of_cars,s.car_id 
from cars c  
join sales s on c.car_id=s.car_id
where s.car_id = 1
group by s.car_id;

select * from salespersons;
select * from cars;
select * from sales;
select * from salespersons;
--4. What are the details of the cars sold by each salesperson? also get the name from 
--other table using third join 

select c.make,c.type,c.style,c.cost,s.sale_id
from cars c 
--left join sales s on c.car_id=s.car_id
join salespersons ss on s.salesman_id=ss.salesman_id;

select c.make,c.type,c.style,c.cost,s.sale_id,ss.name
from cars c 
left join sales s on c.car_id=s.car_id
join salespersons ss on s.salesman_id=ss.salesman_id;

--6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
select * from cars;
select * from sales;
select * from salespersons;

select c.make,c.type,c.style,c.cost,s.sale_id,ss.name
from cars c 
left join sales s on c.car_id=s.car_id
join salespersons ss on s.salesman_id=ss.salesman_id
where year(purchase_date)=2021 and name='emily wong';

--7. What is the total revenue generated by the sales of hatchback cars?
select * from cars;
select * from sales;
select * from salespersons;
select distinct COUNT(car_id) from sales where car_id =2;
select sum(cars.cost) from cars join sales on cars.car_id=sales.car_id where sales.car_id=2;
select cars.car_id,SUM(cars.cost)as revenue from cars 
left join sales on cars.car_id=sales.car_id
where cars.style='hatchback'
group by cars.car_id;

--8. What is the total revenue generated by the sales of SUV cars in the year 2022?
select * from cars;
select * from sales;
select * from salespersons;
select sum(cars.cost) as revenue from sales  join cars on sales.car_id=cars.car_id
where year(purchase_date)=2022 and style='suv';
select distinct COUNT(car_id) from sales where car_id =5;
select distinct COUNT(car_id) from sales where car_id =3;
select sum(cars.cost) from cars join sales on cars.car_id=sales.car_id where cars.style='suv';

--9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?
select * from sales;
select * from salespersons;
select salespersons.name,salespersons.city,count(sales.salesman_id) as counts 
from salespersons 
left join sales 
on salespersons.salesman_id= sales.salesman_id and year(sales.purchase_date)=2023
group by salespersons.name,salespersons.city;

--What is the name and age of the salesperson who generated the highest revenue in the year 2022?
select * from sales;
select * from salespersons;
select * from cars;
--select salespersons.name,salespersons.age from sales 
select salespersons.name,salespersons.age,count(sales.salesman_id) as counts,
sum(cars.cost) as revenue 
from salespersons 
left join sales 
on salespersons.salesman_id= sales.salesman_id and year(sales.purchase_date)=2023
join cars 
on sales.car_id=cars.car_id
group by salespersons.name,salespersons.age;



